# syntax=docker/dockerfile:1

ARG NODE_VERSION=20.11.0

FROM node:${NODE_VERSION}

WORKDIR /usr/src/app

COPY . .

RUN --mount=type=secret,id=github_token \
  cat /run/secrets/github_token
  
CMD  npm install -g typescript && tsc && node dist/src/index.js

EXPOSE 3000