name: deploy

on: 
  push: 
    branches: 
      - master

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd DCM-back
          npm install

      - name: Build TypeScript
        run: |
          cd DCM-back
          npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: |
          cd DCM-back
          npm install

      - name: make db
        run: |
          cd DCM-back
          make db-up
      
      - name: test
        run: |
          cd DCM-back
          npm run test

  buid-docker-img:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build app
        run: |
          cd DCM-back
          docker build


      

      
