name: deploy

on: 
  push: 
    branches: 
      - master

env:
  MJ_APIKEY_PUBLIC: 89224c65a1342099a6edf512c5e36644
  MJ_APIKEY_PRIVATE: fb36ec56d8b913994b2c7b811677ccce
  JWT_KEY: secret_key
  DB: mongoDb
  
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd DCM-back
          npm install

      - name: Build TypeScript
        run: |
          cd DCM-back
          npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: |
          cd DCM-back
          npm install

      - name: make db mysql
        run: |
          cd DCM-back
          make db-up

      - name: make db mongo
        run: |
          cd DCM-back
          make mongo-start

      - name: test
        run: |
          cd DCM-back
          npm run test

  buid-docker-img:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build app
        run: |
          cd DCM-back
          docker build -t nicolas14200/digital_culture_manager:latest .
      
      
      - name: push-dokerhub
        run: |
          docker login --username nicolas14200 --password dckr_pat_Jk8HbkVw1XBbkg71je1Yrcmb0OQ
          docker images
          docker push nicolas14200/digital_culture_manager:latest


      

      
